from enum import Enum


class UserRole(str, Enum):
    CUSTOMER = "CUSTOMER"
    LOGISTICS_MANAGER = "LOGISTICS_MANAGER"
    DRIVER = "DRIVER"
    PORT_OFFICER = "PORT_OFFICER"
    CUSTOMS_OFFICER = "CUSTOMS_OFFICER"
    YARD_MANAGER = "YARD_MANAGER"
    ADMIN = "ADMIN"


class ShipmentStatus(str, Enum):
    REQUEST_SUBMITTED = "REQUEST_SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED"
    PICKUP_EN_ROUTE = "PICKUP_EN_ROUTE"
    GOODS_RELEASED = "GOODS_RELEASED"
    IN_TRANSIT_TO_PORT = "IN_TRANSIT_TO_PORT"
    PORT_ENTRY = "PORT_ENTRY"
    CUSTOMS_CLEARANCE = "CUSTOMS_CLEARANCE"
    IN_YARD = "IN_YARD"
    LOADED_ON_VESSEL = "LOADED_ON_VESSEL"
    IN_TRANSIT_SEA = "IN_TRANSIT_SEA"
    ARRIVED_DEST_PORT = "ARRIVED_DEST_PORT"
    LAST_MILE_ASSIGNED = "LAST_MILE_ASSIGNED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


TERMINAL_STATUSES = {ShipmentStatus.DELIVERED, ShipmentStatus.REJECTED, ShipmentStatus.CANCELLED}


class ContainerStatus(str, Enum):
    EMPTY = "EMPTY"
    LOADED = "LOADED"
    IN_YARD = "IN_YARD"
    ON_VESSEL = "ON_VESSEL"
    DELIVERED = "DELIVERED"


class VesselStatus(str, Enum):
    IN_PORT = "IN_PORT"
    AT_SEA = "AT_SEA"
    APPROACHING = "APPROACHING"


class DocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DocumentType(str, Enum):
    SHIPMENT_REQUEST = "SHIPMENT_REQUEST"
    APPROVAL_FORM = "APPROVAL_FORM"
    DRIVER_ASSIGNMENT = "DRIVER_ASSIGNMENT"
    RELEASE_FORM = "RELEASE_FORM"
    PORT_ENTRY_DECLARATION = "PORT_ENTRY_DECLARATION"
    CUSTOMS_DECLARATION = "CUSTOMS_DECLARATION"
    CUSTOMS_REVIEW = "CUSTOMS_REVIEW"
    CONTAINER_INSPECTION = "CONTAINER_INSPECTION"
    BILL_OF_LADING = "BILL_OF_LADING"
    LOADING_MANIFEST = "LOADING_MANIFEST"
    DEPARTURE_CLEARANCE = "DEPARTURE_CLEARANCE"
    ARRIVAL_CONFIRMATION = "ARRIVAL_CONFIRMATION"
    LAST_MILE_ASSIGNMENT = "LAST_MILE_ASSIGNMENT"
    PROOF_OF_DELIVERY = "PROOF_OF_DELIVERY"


class NotificationType(str, Enum):
    STATUS_CHANGE = "STATUS_CHANGE"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    ALERT = "ALERT"
    INFO = "INFO"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
